// words/data-Y.js

dictionaryDatabase["Y"] = [
    {
        term: "Y-Axis",
        definition: "The vertical axis in a two-dimensional coordinate system."
    },
    {
        term: "Y-Axis Label",
        definition: "The descriptive text identifying the Y-axis in a graph or chart."
    },
    {
        term: "Y-Axis Scale",
        definition: "The measurement interval used along the vertical axis."
    },
    {
        term: "Y-Coordinate",
        definition: "The vertical coordinate representing a position in a Cartesian coordinate system."
    },
    {
        term: "Y-Coordinate Transformation",
        definition: "The conversion of Y-coordinate values between different coordinate systems."
    },
    {
        term: "Y-Dimension",
        definition: "The vertical dimension of an object or graphical element."
    },
    {
        term: "Y-Interpolation",
        definition: "The computation of intermediate values along the Y-axis."
    },
    {
        term: "Y-Offset",
        definition: "The vertical displacement of an object from a reference point."
    },
    {
        term: "Y-Origin",
        definition: "The reference point from which Y-coordinate measurements begin."
    },
    {
        term: "Y-Plane",
        definition: "The luminance component plane in YUV or YCbCr image formats."
    },
    {
        term: "Y-Position",
        definition: "The vertical location of an object in a coordinate system."
    },
    {
        term: "Y-Resolution",
        definition: "The vertical pixel density or resolution of an image or display."
    },
    {
        term: "Y-Split View",
        definition: "A user interface layout divided vertically into separate viewing areas."
    },
    {
        term: "Y-Wireframe Projection",
        definition: "A graphical projection emphasizing the Y-axis orientation of a three-dimensional model."
    },
    {
        term: "Y2K Problem",
        definition: "A software issue caused by representing years with only two digits, potentially leading to incorrect date calculations."
    },
    {
        term: "Y2038 Problem",
        definition: "A limitation in 32-bit Unix time representation that causes timestamp overflow after January 19, 2038."
    },
    {
        term: "YACC (Yet Another Compiler Compiler)",
        definition: "A parser generator that creates syntax analyzers from grammar specifications."
    },
    {
        term: "YACC Grammar",
        definition: "A formal grammar definition used as input to the YACC parser generator."
    },
    {
        term: "YACC Parser",
        definition: "A parser automatically generated by YACC from a grammar specification."
    },
    {
        term: "YAML (YAML Ain't Markup Language)",
        definition: "A human-readable data serialization language commonly used for configuration files."
    },
    {
        term: "YAML API",
        definition: "An application programming interface for reading, writing, or manipulating YAML data."
    },
    {
        term: "YAML Abstract Node",
        definition: "An internal representation of a parsed YAML element."
    },
    {
        term: "YAML Abstract Syntax Tree",
        definition: "A tree representation of a parsed YAML document."
    },
    {
        term: "YAML Alias",
        definition: "A reference to an existing YAML anchor used to avoid duplication."
    },
    {
        term: "YAML Alias Resolution",
        definition: "The process of replacing YAML aliases with their referenced anchors."
    },
    {
        term: "YAML Anchor",
        definition: "A named reference that allows reuse of YAML content."
    },
    {
        term: "YAML Binary Tag",
        definition: "A YAML tag used to represent binary data encoded as text."
    },
    {
        term: "YAML Block Mapping",
        definition: "A key-value mapping expressed using indentation."
    },
    {
        term: "YAML Block Scalar",
        definition: "A multiline string representation in YAML."
    },
    {
        term: "YAML Block Sequence",
        definition: "A list represented using indented dash-prefixed items."
    },
    {
        term: "YAML Boolean Type",
        definition: "The YAML data type representing true or false values."
    },
    {
        term: "YAML Collection",
        definition: "A sequence or mapping structure in a YAML document."
    },
    {
        term: "YAML Comment",
        definition: "A line beginning with # that is ignored during YAML parsing."
    },
    {
        term: "YAML Composer",
        definition: "A parser stage that builds a node graph from parsing events."
    },
    {
        term: "YAML Configuration File",
        definition: "A YAML file used to store application or system configuration settings."
    },
    {
        term: "YAML Configuration Loader",
        definition: "A component that loads application settings from YAML files."
    },
    {
        term: "YAML Configuration Parser",
        definition: "A parser specialized for processing YAML configuration files."
    },
    {
        term: "YAML Constructor",
        definition: "A component that converts parsed YAML nodes into native objects."
    },
    {
        term: "YAML Data Mapping",
        definition: "The association of YAML values with program objects."
    },
    {
        term: "YAML Data Mapping",
        definition: "The association of YAML values with program objects."
    },
    {
        term: "YAML Data Node",
        definition: "An individual value or structure within a YAML document."
    },
    {
        term: "YAML Data Serializer",
        definition: "A component that converts application data into YAML."
    },
    {
        term: "YAML Deserializer",
        definition: "A component that converts YAML data into native program objects."
    },
    {
        term: "YAML Directive",
        definition: "A special instruction that provides metadata about a YAML document."
    },
    {
        term: "YAML Document",
        definition: "A complete unit of structured data written in YAML."
    },
    {
        term: "YAML Document Header",
        definition: "The optional beginning section identifying document directives."
    },
    {
        term: "YAML Document Loader",
        definition: "Software that imports YAML documents into memory."
    },
    {
        term: "YAML Document Separator",
        definition: "The --- marker indicating the beginning of a YAML document."
    },
    {
        term: "YAML Document Terminator",
        definition: "The optional ... marker indicating the end of a YAML document."
    },
    {
        term: "YAML Duplicate Key Detection",
        definition: "Validation that identifies repeated keys within the same mapping."
    },
    {
        term: "YAML Emitter",
        definition: "Software that generates properly formatted YAML output."
    },
    {
        term: "YAML Event Parser",
        definition: "A parser that exposes YAML as a sequence of parsing events."
    },
    {
        term: "YAML Event Stream",
        definition: "A sequence of parsing events generated from a YAML document."
    },
    {
        term: "YAML Float Type",
        definition: "The YAML scalar type representing floating-point numbers."
    },
    {
        term: "YAML Flow Collection",
        definition: "A sequence or mapping written in compact flow style."
    },
    {
        term: "YAML Flow Mapping",
        definition: "A compact mapping representation enclosed in braces."
    },
    {
        term: "YAML Flow Sequence",
        definition: "A compact list representation enclosed in brackets."
    },
    {
        term: "YAML Flow Style",
        definition: "A compact YAML notation using brackets and braces."
    },
    {
        term: "YAML Indentation",
        definition: "The whitespace-based formatting that defines hierarchy in YAML."
    },
    {
        term: "YAML Integer Type",
        definition: "The YAML scalar type representing whole numbers."
    },
    {
        term: "YAML Key",
        definition: "The identifier used to access a value within a YAML mapping."
    },
    {
        term: "YAML Loader",
        definition: "A component that reads and imports YAML documents."
    },
    {
        term: "YAML Loader API",
        definition: "An interface used to load and parse YAML documents."
    },
    {
        term: "YAML Mapping",
        definition: "A collection of key-value pairs in YAML."
    },
    {
        term: "YAML Mapping Node",
        definition: "A node representing a collection of key-value pairs."
    },
    {
        term: "YAML Merge Key",
        definition: "A special key used to merge mappings in YAML."
    },
    {
        term: "YAML Multi-Document Stream",
        definition: "A stream containing multiple YAML documents separated by document markers."
    },
    {
        term: "YAML Node",
        definition: "An individual data element within a YAML document."
    },
    {
        term: "YAML Node Graph",
        definition: "The graph structure representing parsed YAML content."
    },
    {
        term: "YAML Object Mapping",
        definition: "The correspondence between YAML structures and programming language objects."
    },
    {
        term: "YAML Object Serializer",
        definition: "A serializer that converts application objects into YAML."
    },
    {
        term: "YAML Parser",
        definition: "Software that reads and interprets YAML documents."
    },
    {
        term: "YAML Parsing Engine",
        definition: "The core engine responsible for interpreting YAML syntax."
    },
    {
        term: "YAML Parsing Error",
        definition: "An error indicating invalid YAML syntax or structure."
    },
    {
        term: "YAML Path",
        definition: "A logical path used to identify nodes within a YAML structure."
    },
    {
        term: "YAML Plain Scalar",
        definition: "A scalar value written without quotation marks."
    },
    {
        term: "YAML Processing Library",
        definition: "A software library for reading and writing YAML data."
    },
    {
        term: "YAML Quoted Scalar",
        definition: "A scalar enclosed in single or double quotation marks."
    },
    {
        term: "YAML Reference",
        definition: "A reusable value accessed through an alias."
    },
    {
        term: "YAML Resolver",
        definition: "A parser component that determines the type of YAML values."
    },
    {
        term: "YAML Root Node",
        definition: "The top-level node of a YAML document."
    },
    {
        term: "YAML Scalar",
        definition: "A single-value data element such as text, numbers, or booleans."
    },
    {
        term: "YAML Scalar Node",
        definition: "A node containing a single primitive value."
    },
    {
        term: "YAML Schema",
        definition: "A set of rules defining how values are interpreted in YAML."
    },
    {
        term: "YAML Schema Resolver",
        definition: "A component that resolves values according to a selected YAML schema."
    },
    {
        term: "YAML Schema Validator",
        definition: "A tool that validates YAML documents against a schema."
    },
    {
        term: "YAML Sequence",
        definition: "An ordered list of values in YAML."
    },
    {
        term: "YAML Sequence Node",
        definition: "A node representing an ordered collection of values."
    },
    {
        term: "YAML Serialization Format",
        definition: "The standardized representation of structured data in YAML."
    },
    {
        term: "YAML Serialization Engine",
        definition: "A component that converts objects into YAML representation."
    },
    {
        term: "YAML Serializer",
        definition: "A component that converts data structures into YAML format."
    },
    {
        term: "YAML Stream",
        definition: "One or more YAML documents transmitted sequentially."
    },
    {
        term: "YAML Stream Parser",
        definition: "A parser capable of processing multiple YAML documents in sequence."
    },
    {
        term: "YAML Syntax Checker",
        definition: "A tool that verifies the syntax of YAML documents."
    },
    {
        term: "YAML Timestamp Type",
        definition: "A YAML scalar representing date and time values."
    },
    {
        term: "YAML Token",
        definition: "A lexical unit recognized during YAML parsing."
    },
    {
        term: "YAML Tokenizer",
        definition: "Software that converts YAML text into lexical tokens."
    },
    {
        term: "YAML Tree",
        definition: "The hierarchical representation of a YAML document."
    },
    {
        term: "YAML Tree Parser",
        definition: "A parser that constructs a hierarchical tree from YAML input."
    },
    {
        term: "YAML Tree Walker",
        definition: "A utility that traverses the nodes of a YAML document tree."
    },
    {
        term: "YAML Type Tag",
        definition: "A tag explicitly identifying the data type of a YAML value."
    },
    {
        term: "YAML Unicode Support",
        definition: "The ability of YAML to represent Unicode characters."
    },
    {
        term: "YAML Validation Rule",
        definition: "A rule used to verify the correctness of a YAML document."
    },
    {
        term: "YAML Validator",
        definition: "A tool that checks YAML documents for syntax and structural correctness."
    },
    {
        term: "YAML Value",
        definition: "The data associated with a YAML key."
    },
    {
        term: "YAML Value Node",
        definition: "A node containing a scalar value within a YAML structure."
    },
    {
        term: "YAML Version",
        definition: "The specification version implemented by a YAML parser or document."
    },
    {
        term: "YAML Version Directive",
        definition: "A declaration specifying the YAML version used by a document."
    },
    {
        term: "YAML Writer",
        definition: "Software that generates YAML documents."
    },
    {
        term: "YANG (Yet Another Next Generation)",
        definition: "A data modeling language used for configuring and managing network devices."
    },
    {
        term: "YANG Action",
        definition: "A YANG statement defining an operation associated with a data node."
    },
    {
        term: "YANG Augment",
        definition: "A construct that extends an existing YANG data model."
    },
    {
        term: "YANG Choice",
        definition: "A YANG statement that allows one option from multiple alternatives."
    },
    {
        term: "YANG Configuration Data",
        definition: "Device settings represented using a YANG model."
    },
    {
        term: "YANG Configuration Model",
        definition: "A structured representation of network device configuration."
    },
    {
        term: "YANG Configuration Tree",
        definition: "The hierarchical structure of configuration data defined by YANG."
    },
    {
        term: "YANG Connection Validator",
        definition: "A tool that verifies data against YANG model constraints."
    },
    {
        term: "YANG Constraint",
        definition: "A rule restricting valid values or relationships in a YANG model."
    },
    {
        term: "YANG Container",
        definition: "A node grouping related configuration or operational data."
    },
    {
        term: "YANG Data Model",
        definition: "A structured representation of network configuration and state information."
    },
    {
        term: "YANG Data Node",
        definition: "An individual node within a YANG data model."
    },
    {
        term: "YANG Data Store",
        definition: "A repository containing configuration or operational data modeled with YANG."
    },
    {
        term: "YANG Data Tree",
        definition: "The hierarchical organization of nodes defined by a YANG model."
    },
    {
        term: "YANG Enumeration",
        definition: "A user-defined set of named constant values."
    },
    {
        term: "YANG Extension",
        definition: "A user-defined enhancement to the YANG language."
    },
    {
        term: "YANG Feature",
        definition: "A conditional capability defined within a YANG module."
    },
    {
        term: "YANG Feature Flag",
        definition: "A switch that enables or disables optional YANG capabilities."
    },
    {
        term: "YANG Grouping",
        definition: "A reusable collection of YANG definitions."
    },
    {
        term: "YANG Identity",
        definition: "A uniquely named base or derived type in a YANG model."
    },
    {
        term: "YANG Identity Reference",
        definition: "A data type that refers to a defined YANG identity."
    },
    {
        term: "YANG Import",
        definition: "A statement that allows one YANG module to reference another."
    },
    {
        term: "YANG Include",
        definition: "A statement used to include a submodule in a YANG module."
    },
    {
        term: "YANG Instance Data",
        definition: "Runtime data represented according to a YANG model."
    },
    {
        term: "YANG Instance Identifier",
        definition: "A unique path identifying a specific node instance."
    },
    {
        term: "YANG Leaf",
        definition: "A node representing a single data value in a YANG model."
    },
    {
        term: "YANG Leaf-List",
        definition: "A collection of scalar values within a YANG model."
    },
    {
        term: "YANG List",
        definition: "A repeating collection of structured data entries."
    },
    {
        term: "YANG Mandatory Node",
        definition: "A node that must be present in valid configuration data."
    },
    {
        term: "YANG Module",
        definition: "A file containing YANG data model definitions."
    },
    {
        term: "YANG Operational State",
        definition: "Runtime information represented by a YANG model."
    },
    {
        term: "YANG Parser",
        definition: "Software that interprets YANG modules."
    },
    {
        term: "YANG Parser Engine",
        definition: "Software responsible for parsing YANG modules."
    },
    {
        term: "YANG Path Expression",
        definition: "An expression used to reference nodes within a YANG model."
    },
    {
        term: "YANG Revision",
        definition: "A version identifier indicating updates to a YANG module."
    },
    {
        term: "YANG Revision History",
        definition: "The recorded sequence of revisions to a YANG module."
    },
    {
        term: "YANG RPC",
        definition: "A remote procedure call defined using YANG."
    },
    {
        term: "YANG Schema",
        definition: "The complete structure defined by one or more YANG modules."
    },
    {
        term: "YANG Schema Compiler",
        definition: "A component that compiles YANG definitions into usable representations."
    },
    {
        term: "YANG Submodule",
        definition: "A partial YANG definition included within a parent module."
    },
    {
        term: "YANG Tree",
        definition: "The hierarchical organization of nodes within a YANG model."
    },
    {
        term: "YANG Typedef",
        definition: "A user-defined data type declared in YANG."
    },
    {
        term: "YANG Union Type",
        definition: "A type allowing values from multiple underlying data types."
    },
    {
        term: "YANG Validation Engine",
        definition: "Software that validates data using YANG models."
    },
    {
        term: "YARN (Yet Another Resource Negotiator)",
        definition: "Hadoop's resource management framework for scheduling and allocating cluster resources."
    },
    {
        term: "YARN Application",
        definition: "A distributed application executed under YARN resource management."
    },
    {
        term: "YARN Application Attempt",
        definition: "A single execution attempt of a YARN application."
    },
    {
        term: "YARN Application Master",
        definition: "The component that manages the lifecycle of an application running under YARN."
    },
    {
        term: "YARN Application Report",
        definition: "A summary describing the status and execution details of a YARN application."
    },
    {
        term: "YARN Capacity Scheduler",
        definition: "A scheduler that allocates cluster resources based on configured capacities."
    },
    {
        term: "YARN Cluster",
        definition: "A collection of machines managed by YARN."
    },
    {
        term: "YARN Cluster Manager",
        definition: "The component responsible for coordinating resources across a YARN cluster."
    },
    {
        term: "YARN Container",
        definition: "The execution environment allocated for a task within YARN."
    },
    {
        term: "YARN Container Launch",
        definition: "The process of starting a container on a cluster node."
    },
    {
        term: "YARN Container Monitor",
        definition: "A service that observes container resource usage and health."
    },
    {
        term: "YARN Distributed Cache",
        definition: "A mechanism for distributing common application files across cluster nodes."
    },
    {
        term: "YARN Fair Scheduler",
        definition: "A scheduler designed to distribute cluster resources fairly among applications."
    },
    {
        term: "YARN Job History",
        definition: "Records describing completed jobs in a YARN environment."
    },
    {
        term: "YARN Local Resource",
        definition: "A file or archive made available to application containers."
    },
    {
        term: "YARN Log Aggregation",
        definition: "The process of collecting application logs from cluster nodes."
    },
    {
        term: "YARN Node Health Check",
        definition: "A mechanism that monitors the operational status of cluster nodes."
    },
    {
        term: "YARN Node Manager",
        definition: "A service responsible for managing resources on an individual cluster node."
    },
    {
        term: "YARN Queue",
        definition: "A scheduling queue used to organize application execution."
    },
    {
        term: "YARN Queue Capacity",
        definition: "The amount of cluster resources allocated to a scheduling queue."
    },
    {
        term: "YARN Queue Manager",
        definition: "A component responsible for administering scheduling queues."
    },
    {
        term: "YARN Queue Policy",
        definition: "Rules governing resource allocation within a scheduling queue."
    },
    {
        term: "YARN Resource Allocation",
        definition: "The assignment of cluster resources to applications."
    },
    {
        term: "YARN Resource Manager",
        definition: "The central service responsible for resource allocation in a YARN cluster."
    },
    {
        term: "YARN Resource Monitor",
        definition: "A service that tracks resource usage across a cluster."
    },
    {
        term: "YARN Resource Profile",
        definition: "A predefined set of resource requirements for applications."
    },
    {
        term: "YARN Resource Request",
        definition: "A request submitted by an application for computing resources."
    },
    {
        term: "YARN Resource Tracker",
        definition: "A service that records available and allocated cluster resources."
    },
    {
        term: "YARN Scheduler",
        definition: "The component that assigns cluster resources to applications."
    },
    {
        term: "YARN Job Scheduler",
        definition: "A scheduler that determines when and where applications execute."
    },
    {
        term: "YARN Scheduler Policy",
        definition: "The strategy used to distribute cluster resources among applications."
    },
    {
        term: "YARN Service Framework",
        definition: "A framework for running long-lived services on Hadoop clusters."
    },
    {
        term: "YARN Service Registry",
        definition: "A registry that stores information about services running under YARN."
    },
    {
        term: "YARN Timeline Service",
        definition: "A service that stores application execution history and metadata."
    },
    {
        term: "YARN Web Interface",
        definition: "A browser-based interface for monitoring YARN clusters."
    },
    {
        term: "YARN Worker Node",
        definition: "A cluster node that executes application containers."
    },
    {
        term: "YARN Workload Manager",
        definition: "A component that coordinates workload execution across the cluster."
    },
    {
        term: "YCbCr",
        definition: "A color model separating luminance from chrominance components for digital video."
    },
    {
        term: "YCbCr 4:2:0",
        definition: "A chroma subsampling format that reduces color information horizontally and vertically."
    },
    {
        term: "YCbCr 4:2:2",
        definition: "A chroma subsampling format preserving more horizontal color information than 4:2:0."
    },
    {
        term: "YCbCr 4:4:4",
        definition: "A color format that stores full chrominance information without subsampling."
    },
    {
        term: "YCbCr Decoder",
        definition: "A component that converts YCbCr image data into a displayable format."
    },
    {
        term: "YCbCr Encoder",
        definition: "A component that converts image data into the YCbCr color model."
    },
    {
        term: "YCbCr Pixel Format",
        definition: "The arrangement of luminance and chrominance values in YCbCr image data."
    },
    {
        term: "YCbCr Rendering Pipeline",
        definition: "The sequence of operations used to render YCbCr image data."
    },
    {
        term: "YCbCr-to-RGB Conversion Matrix",
        definition: "A transformation matrix used to convert YCbCr values into RGB values."
    },
    {
        term: "Y-Cb-Cr Conversion",
        definition: "The transformation between YCbCr and other color models."
    },
    {
        term: "Yield",
        definition: "The act of voluntarily relinquishing processor control so another task can execute."
    },
    {
        term: "Yield Break",
        definition: "A language construct that terminates an iterator sequence."
    },
    {
        term: "Yield Counter",
        definition: "A metric tracking the number of yield operations performed by a task."
    },
    {
        term: "Yield Decision",
        definition: "The scheduler's determination to transfer execution to another task."
    },
    {
        term: "Yield Event",
        definition: "An event representing the voluntary release of processor execution."
    },
    {
        term: "Yield Flag",
        definition: "An internal indicator showing that a task has yielded execution."
    },
    {
        term: "Yield Function",
        definition: "A function that causes the current thread or task to yield execution."
    },
    {
        term: "Yield Instruction",
        definition: "A processor or programming instruction that hints the scheduler to switch execution."
    },
    {
        term: "Yield Latency",
        definition: "The delay between yielding execution and being scheduled again."
    },
    {
        term: "Yield Mechanism",
        definition: "The implementation enabling a task to relinquish CPU control."
    },
    {
        term: "Yield Optimization",
        definition: "The tuning of scheduling behavior to improve processor utilization."
    },
    {
        term: "Yield Point",
        definition: "A location in program execution where control may be voluntarily transferred."
    },
    {
        term: "Yield Priority",
        definition: "The scheduling priority applied after a task voluntarily yields."
    },
    {
        term: "Yield Queue",
        definition: "A scheduler queue containing yielded tasks awaiting execution."
    },
    {
        term: "Yield Request",
        definition: "A request issued by a task to voluntarily relinquish processor control."
    },
    {
        term: "Yield Resume",
        definition: "The continuation of execution after a yielded task is scheduled again."
    },
    {
        term: "Yield Resume Point",
        definition: "The program location from which execution continues after yielding."
    },
    {
        term: "Yield Return",
        definition: "A language feature that produces values one at a time from an iterator."
    },
    {
        term: "Yield Scheduler",
        definition: "The scheduler component responsible for handling yielded tasks."
    },
    {
        term: "Yield Scheduler Hint",
        definition: "A suggestion from software indicating that execution can be temporarily relinquished."
    },
    {
        term: "Yield State",
        definition: "The execution state of a task that has temporarily relinquished the processor."
    },
    {
        term: "Yield Strategy",
        definition: "A scheduling approach defining when tasks should yield execution."
    },
    {
        term: "Yield Suspension",
        definition: "The temporary suspension resulting from a yield operation."
    },
    {
        term: "Yield Synchronization",
        definition: "The coordination of concurrent tasks using yield operations."
    },
    {
        term: "Yield Timeout",
        definition: "The maximum interval before a yielded task is rescheduled."
    },
    {
        term: "Yield-Based Iterator",
        definition: "An iterator implemented using yield statements."
    },
    {
        term: "Yieldable Task",
        definition: "A task capable of voluntarily giving up processor time."
    },
    {
        term: "Yieldable Thread",
        definition: "A thread designed to support cooperative scheduling."
    },
    {
        term: "Yielding Thread",
        definition: "A thread that voluntarily gives up the CPU before its time slice expires."
    },
    {
        term: "YIQ Color Model",
        definition: "A color space historically used in NTSC television broadcasting."
    },
    {
        term: "YIQ Decoder",
        definition: "A component that converts YIQ signals into displayable image data."
    },
    {
        term: "YIQ Encoder",
        definition: "A component that converts image data into the YIQ color model."
    },
    {
        term: "YIQ Signal",
        definition: "A video signal represented using luminance and chrominance components."
    },
    {
        term: "YIQ-to-RGB Conversion",
        definition: "The process of converting YIQ color values into RGB values."
    },
    {
        term: "Yocto",
        definition: "The SI prefix representing 10\u207B\u00B2\u2074, commonly used in scientific computing."
    },
    {
        term: "Yocto Computing Scale",
        definition: "Computational measurements expressed using yocto-scale units."
    },
    {
        term: "Yocto Data Unit",
        definition: "A data quantity expressed with the yocto SI prefix."
    },
    {
        term: "Yocto Prefix",
        definition: "The SI prefix denoting a factor of 10\u207B\u00B2\u2074."
    },
    {
        term: "Yocto Prefix Conversion",
        definition: "The conversion of values to or from the yocto SI prefix."
    },
    {
        term: "Yocto Storage Unit",
        definition: "A conceptual storage measurement expressed with the yocto prefix."
    },
    {
        term: "Yocto-Scale Measurement",
        definition: "A measurement expressed using yocto units."
    },
    {
        term: "Yoctobyte",
        definition: "A unit equal to 10\u207B\u00B2\u2074 bytes in SI notation."
    },
    {
        term: "Yoctosecond",
        definition: "A unit of time equal to 10\u207B\u00B2\u2074 seconds."
    },
    {
        term: "Yocto Scaling",
        definition: "The use of the yocto prefix to represent extremely small quantities."
    },
    {
        term: "YMODEM",
        definition: "A file transfer protocol that extends XMODEM with larger blocks and batch transfers."
    },
    {
        term: "YMODEM Batch Transfer",
        definition: "The capability of YMODEM to send multiple files in a single session."
    },
    {
        term: "YMODEM Block",
        definition: "A unit of data transmitted during a YMODEM file transfer."
    },
    {
        term: "YMODEM Checksum",
        definition: "An error-detection value used during YMODEM communication."
    },
    {
        term: "YMODEM CRC",
        definition: "A cyclic redundancy check mechanism used for reliable YMODEM transfers."
    },
    {
        term: "YMODEM File Header",
        definition: "Metadata transmitted before file contents in a YMODEM session."
    },
    {
        term: "YMODEM Receiver",
        definition: "The endpoint that receives files using the YMODEM protocol."
    },
    {
        term: "YMODEM Sender",
        definition: "The endpoint that transmits files using the YMODEM protocol."
    },
    {
        term: "YMODEM Session",
        definition: "A complete file transfer interaction using the YMODEM protocol."
    },
    {
        term: "YMODEM Transfer Block",
        definition: "A block of data transmitted during a YMODEM session."
    },
    {
        term: "YMODEM Transfer Session",
        definition: "The complete communication cycle of a YMODEM file transfer."
    },
    {
        term: "Yotta",
        definition: "The SI prefix representing 10\u00B2\u2074, used to denote extremely large quantities."
    },
    {
        term: "Yotta Archive",
        definition: "A conceptual archive measured in yottabyte-scale storage."
    },
    {
        term: "Yotta Archive Format",
        definition: "A conceptual archive format intended for yotta-scale datasets."
    },
    {
        term: "Yotta Backup System",
        definition: "A conceptual backup system designed for yotta-scale storage."
    },
    {
        term: "Yotta Cache",
        definition: "A conceptual cache operating at yotta-scale capacity."
    },
    {
        term: "Yotta Cluster",
        definition: "A conceptual computing cluster operating at yotta-scale capacity."
    },
    {
        term: "Yotta Compute Cluster",
        definition: "A conceptual cluster capable of yotta-scale computation."
    },
    {
        term: "Yotta Computing",
        definition: "Computing involving resources measured on the yotta scale."
    },
    {
        term: "Yotta Data Capacity",
        definition: "Data storage measured in yottabytes."
    },
    {
        term: "Yotta Data Processing",
        definition: "Data processing at yottabyte or yotta-operation scale."
    },
    {
        term: "Yotta Data Repository",
        definition: "A conceptual repository storing yotta-scale datasets."
    },
    {
        term: "Yotta File System",
        definition: "A conceptual file system supporting yottabyte-scale storage."
    },
    {
        term: "Yotta Memory Architecture",
        definition: "A conceptual memory architecture supporting yotta-scale capacities."
    },
    {
        term: "Yotta Memory Scale",
        definition: "Memory capacity represented using yotta-scale units."
    },
    {
        term: "Yotta Network Throughput",
        definition: "Network bandwidth expressed in yotta-scale units."
    },
    {
        term: "Yotta Prefix",
        definition: "The SI prefix denoting a factor of 10\u00B2\u2074."
    },
    {
        term: "Yotta Processing Node",
        definition: "A conceptual compute node in a yotta-scale environment."
    },
    {
        term: "Yotta Processing Power",
        definition: "Computational capability measured in yotta-scale operations."
    },
    {
        term: "Yotta Storage Array",
        definition: "A theoretical storage array capable of yottabyte-scale capacity."
    },
    {
        term: "Yotta Storage System",
        definition: "A theoretical storage infrastructure capable of handling yottabyte-scale data."
    },
    {
        term: "Yotta Transfer Pipeline",
        definition: "A conceptual pipeline for yotta-scale data movement."
    },
    {
        term: "Yotta Transfer Rate",
        definition: "A data transmission rate measured in yotta-scale units."
    },
    {
        term: "Yotta Unit Prefix",
        definition: "The SI prefix representing 10\u00B2\u2074."
    },
    {
        term: "Yottabit",
        definition: "A unit equal to 10\u00B2\u2074 bits."
    },
    {
        term: "Yottabyte",
        definition: "A unit equal to 10\u00B2\u2074 bytes."
    },
    {
        term: "YottaFLOPS",
        definition: "A computational performance measure equal to 10\u00B2\u2074 floating-point operations per second."
    },
    {
        term: "YottaHertz",
        definition: "A unit of frequency equal to 10\u00B2\u2074 hertz."
    },
    {
        term: "YottaScale Computing",
        definition: "Computing involving storage or processing capacities measured in yotta-scale units."
    },
    {
        term: "Yotta-Scale Storage",
        definition: "Storage capacity measured in yottabytes."
    },
    {
        term: "Yotta-Scale Throughput",
        definition: "Data transfer measured in yotta-scale units."
    },
    {
        term: "Yotta-Zetta Conversion",
        definition: "The conversion between yotta (10\u00B2\u2074) and zetta (10\u00B2\u00B9) measurement units."
    },
    {
        term: "YubiKey",
        definition: "A hardware security key used for strong authentication and passwordless login."
    },
    {
        term: "YubiKey Authentication",
        definition: "The process of verifying identity using a YubiKey device."
    },
    {
        term: "YubiKey Challenge-Response",
        definition: "An authentication mode where a YubiKey generates a response to a challenge."
    },
    {
        term: "YubiKey Configuration",
        definition: "The settings that define the behavior of a YubiKey device."
    },
    {
        term: "YubiKey Credential",
        definition: "A cryptographic credential securely stored on a YubiKey."
    },
    {
        term: "YubiKey Device Manager",
        definition: "Software used to configure and manage YubiKey devices."
    },
    {
        term: "YubiKey FIDO U2F",
        definition: "The Universal 2nd Factor authentication capability provided by a YubiKey."
    },
    {
        term: "YubiKey FIDO2",
        definition: "The FIDO2 authentication capability provided by a YubiKey device."
    },
    {
        term: "YubiKey Firmware",
        definition: "The embedded software controlling YubiKey functionality."
    },
    {
        term: "YubiKey Hardware Token",
        definition: "A physical authentication device manufactured by Yubico."
    },
    {
        term: "YubiKey Management Tool",
        definition: "A utility for administering YubiKey settings and applications."
    },
    {
        term: "YubiKey NFC",
        definition: "A YubiKey model supporting Near Field Communication."
    },
    {
        term: "YubiKey OTP",
        definition: "A one-time password generated by a YubiKey."
    },
    {
        term: "YubiKey PIN",
        definition: "A personal identification number protecting secure functions on a YubiKey."
    },
    {
        term: "YubiKey PIV",
        definition: "The Personal Identity Verification functionality supported by a YubiKey."
    },
    {
        term: "YubiKey Resident Credential",
        definition: "A credential securely stored on the YubiKey itself."
    },
    {
        term: "YubiKey Security Key",
        definition: "A YubiKey configured for FIDO-based authentication."
    },
    {
        term: "YubiKey Security Policy",
        definition: "The configuration governing YubiKey authentication behavior."
    },
    {
        term: "YubiKey Slot",
        definition: "A programmable storage location for credentials on a YubiKey."
    },
    {
        term: "YubiKey Smart Card Mode",
        definition: "The operating mode providing smart card functionality through PIV."
    },
    {
        term: "YubiKey Touch Event",
        definition: "User interaction with a YubiKey to confirm an authentication request."
    },
    {
        term: "YubiKey USB Interface",
        definition: "The USB connection used for communication with a YubiKey."
    },
    {
        term: "Yubico Authenticator",
        definition: "An application used to manage authentication credentials stored on YubiKey devices."
    },
    {
        term: "Yubico FIDO Authenticator",
        definition: "A Yubico implementation supporting FIDO authentication standards."
    },
    {
        term: "Yubico OTP",
        definition: "A proprietary one-time password protocol developed by Yubico."
    },
    {
        term: "Yubico Validation Server",
        definition: "A server that verifies Yubico OTP authentication requests."
    },
    {
        term: "Yule-Walker Equation",
        definition: "A set of equations used to estimate parameters of autoregressive models in signal processing."
    },
    {
        term: "YUV",
        definition: "A color encoding model separating brightness and color information."
    },
    {
        term: "YUV Chroma Channel",
        definition: "One of the chrominance channels in YUV image data."
    },
    {
        term: "YUV Chroma Plane",
        definition: "The chrominance component stored separately in planar YUV formats."
    },
    {
        term: "YUV Chroma Subsampling",
        definition: "The reduction of color resolution relative to brightness information."
    },
    {
        term: "YUV Color Conversion",
        definition: "The process of converting YUV data to or from another color space."
    },
    {
        term: "YUV Color Matrix",
        definition: "A matrix used to convert between YUV and other color spaces."
    },
    {
        term: "YUV Component Order",
        definition: "The sequence in which Y, U, and V components are stored."
    },
    {
        term: "YUV Conversion Matrix",
        definition: "A mathematical transformation matrix used for color conversion."
    },
    {
        term: "YUV Decoder",
        definition: "A component that interprets image or video data encoded in the YUV format."
    },
    {
        term: "YUV Decoder Buffer",
        definition: "A temporary buffer used during YUV decoding."
    },
    {
        term: "YUV Decoder Pipeline",
        definition: "The sequence of stages used to decode YUV image or video data."
    },
    {
        term: "YUV Encoder",
        definition: "A component that converts image data into the YUV color format."
    },
    {
        term: "YUV Encoding Pipeline",
        definition: "The sequence of stages used to produce YUV-formatted output."
    },
    {
        term: "YUV Frame",
        definition: "A single image frame represented using YUV color components."
    },
    {
        term: "YUV Frame Buffer",
        definition: "Memory allocated to store YUV image frames."
    },
    {
        term: "YUV Frame Decoder",
        definition: "A component that decodes individual YUV video frames."
    },
    {
        term: "YUV Frame Encoder",
        definition: "A component that encodes frames into the YUV format."
    },
    {
        term: "YUV Frame Sequence",
        definition: "An ordered collection of YUV video frames."
    },
    {
        term: "YUV Image",
        definition: "An image stored using the YUV color model."
    },
    {
        term: "YUV Image Buffer",
        definition: "A memory buffer containing image data in YUV format."
    },
    {
        term: "YUV Image Decoder",
        definition: "Software that decodes YUV-formatted image data."
    },
    {
        term: "YUV Image Encoder",
        definition: "Software that converts image data into YUV format."
    },
    {
        term: "YUV Image Plane",
        definition: "A separate memory plane containing one YUV component."
    },
    {
        term: "YUV Luma Plane",
        definition: "The plane containing luminance information in YUV data."
    },
    {
        term: "YUV Memory Layout",
        definition: "The arrangement of YUV data within memory."
    },
    {
        term: "YUV Pixel Buffer",
        definition: "A memory area containing YUV pixel values."
    },
    {
        term: "YUV Pixel Converter",
        definition: "A utility that converts pixel values to or from the YUV format."
    },
    {
        term: "YUV Pixel Format",
        definition: "The layout of luminance and chrominance values for pixels in YUV data."
    },
    {
        term: "YUV Pixel Layout",
        definition: "The arrangement of luminance and chrominance values in memory."
    },
    {
        term: "YUV Pixel Stride",
        definition: "The memory distance between adjacent pixels in YUV data."
    },
    {
        term: "YUV Planar Format",
        definition: "A YUV layout storing luminance and chrominance in separate planes."
    },
    {
        term: "YUV Plane",
        definition: "An individual luminance or chrominance component stored separately in YUV images."
    },
    {
        term: "YUV Plane Offset",
        definition: "The memory offset at which a YUV plane begins."
    },
    {
        term: "YUV Processing Pipeline",
        definition: "A sequence of operations for manipulating YUV image data."
    },
    {
        term: "YUV Renderer",
        definition: "Software or hardware that displays YUV-formatted images or video."
    },
    {
        term: "YUV Renderer Pipeline",
        definition: "The sequence of rendering stages for YUV image data."
    },
    {
        term: "YUV Rendering Pipeline",
        definition: "The sequence of operations used to display YUV image data."
    },
    {
        term: "YUV Row Stride",
        definition: "The number of bytes occupied by one row of YUV pixel data."
    },
    {
        term: "YUV Sampling",
        definition: "The technique used to determine how chrominance values are stored relative to luminance."
    },
    {
        term: "YUV Sampling Format",
        definition: "The organization of chroma subsampling in a YUV image."
    },
    {
        term: "YUV Stream",
        definition: "A continuous sequence of YUV-formatted image or video frames."
    },
    {
        term: "YUV Surface",
        definition: "A graphics surface storing pixel data in YUV format."
    },
    {
        term: "YUV Texture",
        definition: "A graphics texture whose pixel data is stored in YUV format."
    },
    {
        term: "YUV Video",
        definition: "Video encoded or processed using the YUV color model."
    },
    {
        term: "YUV Video Buffer",
        definition: "A memory area allocated for YUV video frames."
    },
    {
        term: "YUV Zero Padding",
        definition: "The addition of zero values to align YUV data structures."
    },
    {
        term: "YUV-to-RGB Conversion",
        definition: "The transformation of YUV color values into the RGB color space."
    },
    {
        term: "YUV420",
        definition: "A YUV format using 4:2:0 chroma subsampling."
    },
    {
        term: "YUV420 Chroma Plane",
        definition: "The chrominance plane used in the YUV420 format."
    },
    {
        term: "YUV420 Decoder",
        definition: "A decoder for processing YUV420-encoded video frames."
    },
    {
        term: "YUV420 Encoder",
        definition: "A component that generates video in the YUV420 format."
    },
    {
        term: "YUV420 Planar Format",
        definition: "A planar YUV format using 4:2:0 chroma subsampling."
    },
    {
        term: "YUV420 Tile",
        definition: "A tiled memory layout for storing YUV420 image data."
    },
    {
        term: "YUV422",
        definition: "A YUV format using 4:2:2 chroma subsampling."
    },
    {
        term: "YUV422 Decoder",
        definition: "A component that decodes video encoded in the YUV422 format."
    },
    {
        term: "YUV422 Encoder",
        definition: "A component that converts image data into the YUV422 format."
    },
    {
        term: "YUV422 Packed Format",
        definition: "A packed representation of YUV data using 4:2:2 chroma sampling."
    },
    {
        term: "YUV444",
        definition: "A YUV format storing full-resolution luminance and chrominance data."
    },
    {
        term: "YUV444 Renderer",
        definition: "A rendering component that displays full-resolution YUV444 image data."
    },
    {
        term: "YUV444 Texture",
        definition: "A graphics texture that stores image data in the YUV444 color format."
    },
    {
        term: "YUV444 Video Stream",
        definition: "A video stream encoded using full-resolution YUV444 sampling."
    },
    {
        term: "Yule-Walker Equation",
        definition: "A set of equations used to estimate parameters of autoregressive models in signal processing."
    },
];